spring.datasource.url=jdbc:postgresql://localhost:5432/devutec
spring.datasource.username=devutec
spring.datasource.password=devutec
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true