spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/devutec}
spring.datasource.username=${DB_USERNAME:devutec}
spring.datasource.password=${DB_PASSWORD:devutec}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
jwt.secret=${JWT_SECRET: cambia-este-texto-por-algo-random-de-al-menos-32-caracteres}
jwt.access-expiration-ms=900000
jwt.refresh-expiration-ms=604800000